### ISSUE TITLE
Bot crashing periodically

### ISSUE THREAD

**Issue by thejhh** [mmalecki/dmkbot#4]
The bot is crashing almost hourly with the message:

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ETIMEDOUT, Connection timed out
    at Socket._onConnect (net.js:601:18)
    at IOWatcher.onWritable [as callback] (net.js:186:12)
```

I'm not sure where the problem actually is. When this happens it usually does the same again right away and IRC channel has join and part flood for some minutes because I am using simple shell script to restart the bot if it crashes.

I am using only rss module.

**Comment by mmalecki** [comment]
I'm aware of this issue and I've been trying to debug it for some time. It may be caused by node-irc.
I'm pretty sure that those are not _real_ timeouts. I'll try looking into it today.

**Comment by thejhh** [comment]
This might be a bug in Node itself. I wound similar bug discussion for Node in general when I was debugging this:

http://groups.google.com/group/nodejs/browse_thread/thread/bbefa671f73662d

Also this looks like the same as [socket.io-client issue #177](https://github.com/LearnBoost/socket.io-client/issues/177). (If it's the same and they fix it there it might help fixing it here, too.)

**Comment by thejhh** [comment]
Hmm, actually that socket.io-client issue has been closed already.
